import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	loginscreen: {
		flex: 1,
		backgroundColor: "#EEF1FF",
		alignItems: "center",
		justifyContent: "center",
		padding: 12,
		width: "100%",
	},
	loginheading: {
		fontSize: 26,
		marginBottom: 10,
	},
	logininputContainer: {
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
	},
	logininput: {
		borderWidth: 1,
		width: "90%",
		padding: 8,
		borderRadius: 2,
	},
	loginbutton: {
		backgroundColor: "green",
		padding: 12,
		marginVertical: 10,
		width: "60%",
		borderRadius: "50%",
		elevation: 1,
	},
	loginbuttonText: {
		textAlign: "center",
		color: "#fff",
		fontWeight: "600",
	},
	chatscreen: {
		backgroundColor: "#F7F7F7",
		flex: 1,
		padding: 10,
		position: "relative",
	},
	chatheading: {
		fontSize: 24,
		fontWeight: "bold",
		color: "green",
	},
	chattopContainer: {
		backgroundColor: "#F7F7F7",
		height: 70,
		width: "100%",
		padding: 20,
		justifyContent: "center",
		marginBottom: 15,
		elevation: 2,
	},
	chatheader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
	},
	chatlistContainer: {
		paddingHorizontal: 10,
	},
	chatemptyContainer: {
		width: "100%",
		height: "80%",
		alignItems: "center",
		justifyContent: "center",
	},
	chatemptyText: { 
		fontWeight: "bold", 
		fontSize: 24, 
		paddingBottom: 30 
	},
	messagingscreen: {
		flex: 1,
	},
	messaginginputContainer: {
		width: "100%",
		minHeight: 100,
		backgroundColor: "white",
		paddingVertical: 30,
		paddingHorizontal: 15,
		justifyContent: "center",
		flexDirection: "row",
	},
	messaginginput: {
		borderWidth: 1,
		padding: 15,
		flex: 1,
		marginRight: 10,
		borderRadius: 20,
	},
	messagingbuttonContainer: {
		width: "30%",
		backgroundColor: "green",
		borderRadius: 5,
		alignItems: "center",
		justifyContent: "center",
		borderRadius: 50,
	},
	modalbutton: {
		width: "40%",
		height: 45,
		backgroundColor: "green",
		borderRadius: 5,
		alignItems: "center",
		justifyContent: "center",
		color: "#fff",
	},
	modalbuttonContainer: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginTop: 20,
	},
	modaltext: {
		color: "#fff",
	},
	modalContainer: {
		paddingLeft: 10,
		paddingRight: 10,
		width: "100%",
		borderTopColor: "#F7F7FC",
		elevation: 1,
		height: 150,
		backgroundColor: "#0F1828",
		position: "absolute",
		bottom: 0,
		zIndex: 10,
	},
	modalinput: {
		borderWidth: 1,
		borderColor: "#F7F7FC",
		borderRadius: 4,
		padding: 15,
		color: '#F7F7FC',
	},
	modalsubheading: {
		fontSize: 14,
		fontWeight: "bold",
		marginBottom: 15,
		marginTop: 15,
		textAlign: "center",
		color: '#F7F7FC',
	},
	mmessageWrapper: {
		width: "100%",
		alignItems: "flex-start",
		marginBottom: 15,
	},
	mmessage: {
		maxWidth: "50%",
		backgroundColor: "#f5ccc2",
		padding: 15,
		borderRadius: 10,
		marginBottom: 2,
	},
	mvatar: {
		marginRight: 5,
	},
	cchat: {
		width: "100%",
		flexDirection: "row",
		alignItems: "center",
		borderRadius: 5,
		paddingHorizontal: 15,
		backgroundColor: "#fff",
		height: 80,
		marginBottom: 10,
	},
	cavatar: {
		marginRight: 15,
	},
	cusername: {
		fontSize: 18,
		marginBottom: 5,
		fontWeight: "bold",
	},
	cmessage: {
		fontSize: 14,
		opacity: 0.7,
	},
	crightContainer: {
		flexDirection: "row",
		justifyContent: "space-between",
		flex: 1,
	},
	ctime: {
		opacity: 0.5,
	},
});